name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем свежий код
        uses: actions/checkout@v3
      - name: Логинимся в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Собираем и отправляем образ
        run: |
          docker build -t flock21/portfolio:latest .
          docker push flock21/portfolio:latest
